# Generated by Django 5.2.4 on 2025-10-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
        ('users', '0003_create_superuser'),
    ]

    operations = [
    ]
