# Generated by Django 5.2.4 on 2025-10-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_seat_is_booked_seat_reserved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
