# Generated by Django 5.2.4 on 2025-10-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_booking_booking_id_alter_movie_youtube_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
    ]
